spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    druid:
      url: jdbc:mysql://localhost:3306/one_piece?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC
      max-active: 100
      query-timeout: 50
  redis:
    database: 0
    host: 127.0.0.1
    lettuce:
      pool:
        max-idle: 8
        max-wait: -1
    port: 6379
    timeout: 5000

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
